spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/willwbowen/config-repo
          searchPaths: '/,{application}'
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"