apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configsvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configsvr
  template:
    metadata:
      labels:
        app: configsvr
    spec:
      containers:
        - name: configsvr
          image: willwbowen/salonapi-configsvr
          ports:
            - containerPort: 8888
          env:
          - name: CONFIGSERVER_PORT
            value: "8888"
          - name: CONFIGSERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: configsvr
                key: password
          - name: ENCRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: configsvr
                key: encrypt-key
