apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: willwbowen/salonapi-configsvr
          ports:
            - containerPort: 8888
          env:
          - name: CONFIGSERVER_PORT
            valueFrom:
              configKeyRef:
                name: configserver
                key: port
          - name: CONFIGSERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: configserver
                key: password
          - name: ENCRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: configserver
                key: encrypt-key
