apiVersion: v1
kind: Service
metadata:
  name: configsvr-service
  labels:
    app: configsvr
spec:
  type: NodePort
  ports:
  - port: $CONFIGSERVER_PORT
    nodePort: 30001
    protocol: TCP
  selector:
    app: configsvr
