apiVersion: v1
kind: Service
metadata:
  name: configsvr-service
  labels:
    app: configsvr
spec:
  type: NodePort
  ports:
  - name: configsvr
    port: $CONFIGSERVER_PORT
    nodePort: $CONFIGSERVER_PORT
    protocol: TCP
  selector:
    app: configsvr
