apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30001
    protocol: TCP
  selector:
    app: configserver
